"""
Production Prometheus Exporter & OpenTelemetry Metric Instrumentation.
Phase 53: Monitoring Stack.
"""
from __future__ import annotations
import logging
from typing import Dict
from prometheus_client import Counter, Gauge, Histogram, generate_latest, CollectorRegistry

logger = logging.getLogger("CryptoScope.Prometheus")

# Dedicated registry to prevent global namespace collisions
PROD_REGISTRY = CollectorRegistry()

# 1. Market Ingestion & Feeds
FEED_MESSAGES_TOTAL = Counter(
    "cryptoscope_feed_messages_total",
    "Total raw messages received from venues",
    ["provider", "stream"],
    registry=PROD_REGISTRY
)
FEED_LATENCY_MS = Gauge(
    "cryptoscope_feed_latency_ms",
    "Venue to server ingestion latency in milliseconds",
    ["provider"],
    registry=PROD_REGISTRY
)
FEED_HEALTH_STATUS = Gauge(
    "cryptoscope_feed_healthy",
    "Provider health status (1 = Healthy, 0 = Unhealthy)",
    ["provider"],
    registry=PROD_REGISTRY
)

# 2. Online Feature Store
FEATURE_FRESHNESS_SECONDS = Gauge(
    "cryptoscope_feature_freshness_seconds",
    "Age of online feature in seconds",
    ["symbol", "feature_name"],
    registry=PROD_REGISTRY
)

# 3. Model Serving & Latency
INFERENCE_LATENCY_MS = Histogram(
    "cryptoscope_inference_latency_ms",
    "Model inference latency breakdown in milliseconds",
    ["stage"],
    buckets=[1.0, 5.0, 10.0, 25.0, 50.0, 100.0, 250.0],
    registry=PROD_REGISTRY
)
ACTIVE_CHAMPION_INFO = Gauge(
    "cryptoscope_active_champion_info",
    "Currently active production champion model",
    ["asset", "horizon", "model_id"],
    registry=PROD_REGISTRY
)

# 4. Predictions & Signals
PREDICTIONS_SERVED_TOTAL = Counter(
    "cryptoscope_predictions_total",
    "Total predictions generated by the serving engine",
    ["asset", "horizon", "decision"],
    registry=PROD_REGISTRY
)
BRIER_SCORE_ROLLING = Gauge(
    "cryptoscope_rolling_brier_score",
    "Rolling 100-sample Brier score",
    ["asset", "horizon"],
    registry=PROD_REGISTRY
)
MCC_SCORE_ROLLING = Gauge(
    "cryptoscope_rolling_mcc_score",
    "Rolling 100-sample Matthews Correlation Coefficient",
    ["asset", "horizon"],
    registry=PROD_REGISTRY
)

# 5. Paper Trading
PAPER_EQUITY_USD = Gauge(
    "cryptoscope_paper_equity_usd",
    "Real-time marked paper trading account equity",
    registry=PROD_REGISTRY
)


def export_prometheus_metrics() -> str:
    """Generate Prometheus exposition text format."""
    return generate_latest(PROD_REGISTRY).decode("utf-8")
